CREATE TABLE TNotice(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(200) NOT NULL,
	Content NVARCHAR(4000) NULL,
	LastUpdateDate DATETIME NULL,
	LastUpdateBy NVARCHAR(20) NULL,
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	CreateBy NVARCHAR(20) NOT NULL
)

CREATE TABLE TBanner(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(200) NOT NULL,
	LinkUrl NVARCHAR(500) NULL,
	ImgSrc NVARCHAR(500) NOT NULL,
	[Order] INT NOT NULL DEFAULT(1),
	PositionKey VARCHAR(30) NOT NULL,
	LastUpdateDate DATETIME NULL,
	LastUpdateBy NVARCHAR(20) NULL,
	CreateDate DATETIME NOT NULL DEFAULT(GETDATE()),
	CreateBy NVARCHAR(20) NOT NULL
)