//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siteo.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteoEntities : DbContext
    {
        public SiteoEntities()
            : base("name=SiteoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBanner> TBanners { get; set; }
        public virtual DbSet<TNotice> TNotices { get; set; }
        public virtual DbSet<TAdminUser> TAdminUsers { get; set; }
        public virtual DbSet<TAdminUserRole> TAdminUserRoles { get; set; }
        public virtual DbSet<TModule> TModules { get; set; }
        public virtual DbSet<TPermission> TPermissions { get; set; }
        public virtual DbSet<TPermissionnModule> TPermissionnModules { get; set; }
        public virtual DbSet<TRole> TRoles { get; set; }
        public virtual DbSet<TRolePermission> TRolePermissions { get; set; }
    }
}
