//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siteo.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteoEntities : DbContext
    {
        public SiteoEntities()
            : base("name=SiteoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAdminUser> TAdminUser { get; set; }
        public virtual DbSet<TAdminUserRole> TAdminUserRole { get; set; }
        public virtual DbSet<TBanner> TBanner { get; set; }
        public virtual DbSet<TModule> TModule { get; set; }
        public virtual DbSet<TNews> TNews { get; set; }
        public virtual DbSet<TNewsPictures> TNewsPictures { get; set; }
        public virtual DbSet<TNewsType> TNewsType { get; set; }
        public virtual DbSet<TNotice> TNotice { get; set; }
        public virtual DbSet<TPermission> TPermission { get; set; }
        public virtual DbSet<TRole> TRole { get; set; }
        public virtual DbSet<TRolePermission> TRolePermission { get; set; }
    }
}
